export const SET_LOADING_LIST_ITEM = 'SET_LOADING_LIST_ITEM';
export const SET_INITIAL_LIST_ITEM = 'SET_INITIAL_LIST_ITEM';
export const LIST_ITEM_TOGGLE = 'LIST_ITEM_TOGGLE';
export const ADD_NEW_LIST_ITEM = 'ADD_NEW_LIST_ITEM';
export const EDIT_LIST_ITEM = 'EDIT_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
